# Harmony Jekyll theme general configurations 

# Base URL
baseurl: ""

# Site live URL
url: http://georgeyk.com.br

# Localhost 
# url: http://127.0.0.1:4000  

# Harmony theme configuration. Please change accordingly.
harmony:
  name: George Y. Kussumoto
  # Little description about your site
  description: George Y. Kussumoto
  meta_description: George Y. Kussumoto
  basetheme: darken # pre defined thmes are darken, blue-water, redish.
  author: # Author details
    name: George Y. Kussumoto
    email: contato@georgeyk.com.br
    url: http://georgeyk.com.br

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-23747770-1

  # Profile links, leave blank to ignore
  social: 
    github: georgeyk
    twitter: georgekussumoto
    facebook: george.kussumoto
    gplus: +110804354108135455271
    dribble:
    pinterest: 
  # Toggle disclaimer in footer
  show_disclaimer: true

# Conversion / Build settings 
markdown:    kramdown
highlighter: pygments # this is how you put pygments config in jekyll 2.0 instead of pygments: true

# Permalinks
permalink:        pretty

exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed
